### ISSUE TITLE
Allow each GEP remote to have more than 1 valid Certificate.

### ISSUE THREAD

**Issue by StevenChisholm** [GridProtectionAlliance/SIEGate#5]
Currently, if I need to update the x509 Certificate for SIEGATE, this would require all parties to schedule the same downtime during this certificate change. This will be an operational nightmare. It would be better if a single connection can have 2 valid client certificates at a time. Then I could notify all parties that on a specific date, I'll be changing my server certificate. This would give them time to add the .cer file to their remote SIEGate servers before the change over.

**Comment by ritchiecarroll** [comment]
A little confused on this one as you can already do this today simply by having two (or more) valid certificates with associated `Subscriber` records.

Think I'll close this one unless I missed your point.
